Added http proxy configuration
crawler-commons/http-fetcher pull request #9
Opened 2016-12-07 21:52 UTC by aecio

Solves issue #8

2016-12-08 03:05 UTC, kkrugler commented
Hi @aecio - until (or if) we get rid of BaseHttpFetcher, I think it would be more consistent to add the setProxy() call to BaseHttpFetcher, and just use the (protected) proxy variable in SimpleHttpFetcher when building the client.

2016-12-12 21:12 UTC, aecio commented
@kkrugler Just fixed that.
I agree BaseHttpFetcher could removed, I see no use for it.

2016-12-12 21:52 UTC, kkrugler commented
Hi @aecio - the main value I see for BaseHttpFetcher is if someone wanted to create a radically different fetcher (still based on HttpClient, e.g. the async version). Then having this base class to store settings common across both versions would be better.

There's a minor value in that it makes it easier to create a fake fetcher (if you don't want to real mocking support), which I've done in the past when building fetchers that use this code.

2016-12-13 03:12 UTC, aecio commented
@kkrugler - I see your point. I usually prefer to use interfaces and composition for these cases. I have more than one "HTTP fetcher" implementation in the crawler I work on, but currently I just use `BaseFetcher`. I use it mainly because of the fetcher signature (it could be just an interface instead of a abstract class), I find the configurations too specific for the  `SimpleHttpFetcher` implementation. But anyway, it may be useful for other cases.

2016-12-13 04:31 UTC, kkrugler commented
Sorry, should have noticed this before...minor nit:

Use leading "_" for instance variables (so proxy => _proxy).

Hmm, wonder if I've got what it takes to add checkstyle to the pom?

2017-08-23 15:08 UTC, afs commented
An alternative is to enable system properties.  The change is `HttpClientBuilder.create().useSystemProperties()` to pick up the "http.proxy" settings.

2018-05-14 00:41 UTC, aecio commented
@kkrugler Just pushed a fix for the leading `_` formatting problem. Sorry for taking so long, I completely forgot about this.

2018-05-14 14:52 UTC, kkrugler commented on src/main/java/crawlercommons/fetcher/http/BaseHttpFetcher.java
> +        this._proxy = new HttpHost(host, port, scheme);
No need for `this.`, which is one of the reasons we use a leading `_`.

Also would be good to have a `getProxy()` call.

2018-05-14 14:53 UTC, kkrugler commented on src/main/java/crawlercommons/fetcher/http/SimpleHttpFetcher.java
> +                if(_proxy != null){
Minor nit - consistent formatting would be `if (_proxy != null) {`

2018-05-14 14:55 UTC, kkrugler requested changes
Some minor nits, but we also need an update to CHANGES.txt

2021-01-09 22:32 UTC, merged